services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: antman
      POSTGRES_PASSWORD: antman
